name: 'SemVersion'
description: 'GitHub Action to find the next version of your project using Conventional Commit'
author: 'shiipou'

inputs:
  ALLOW_FAILURE:
    description: 'If set to "true" and this action was run on incorrect state, the action will fail. Else, it just skip.'
    required: false
    default: "true"
  LEVEL_0:
    description: "The regex to find commit type that won't increment any version tag."
    required: false
    default: '^(build|ci|docs|style|refactor|test|chore)$'
  LEVEL_1:
    description: "The regex to find commit type that will increment patch version tag."
    required: false
    default: '^(fix|perf)$'
  LEVEL_2:
    description: "The regex to find commit type that will increment minor version tag."
    required: false
    default: '^(feat)$'
  LEVEL_3:
    description: "The regex to find commit type that will increment major version tag."
    required: false
    default: "^.+!$"
  RELEASE_BRANCHES_REGEX:
    description: "The regex to find the release branch."
    required: false
    default: '^(main)$'
  PRERELEASE_BRANCHES_REGEX:
    description: "The regex to find the pre-release branch."
    required: false
    default: '^(rc|beta|hotfix)$'
  DEBUG:
    description: 'If set, will show more info about running action'
    required: false
outputs:
  VERSION:
    description: 'The next version find by semantic-release'
    value: ${{ steps.semantic-release.outputs.VERSION }}
  WILL_RELEASE:
    description: 'Only set to "true" if the release tag will be released'
    value: ${{ steps.semantic-release.outputs.WILL_RELEASE }}
  IS_PRE_RELEASE:
    description: 'Only set to "true" if the release tag will be a pre-release'
    value: ${{ steps.semantic-release.outputs.IS_PRE_RELEASE }}

runs:
  using: "composite"
  steps:
    - name: Semantic-Release
      id: semantic-release
      shell: bash
      env:
        ALLOW_FAILURE: '${{ inputs.ALLOW_FAILURE }}'
        LEVEL_0: '${{ inputs.LEVEL_0 }}'
        LEVEL_1: '${{ inputs.LEVEL_1 }}'
        LEVEL_2: '${{ inputs.LEVEL_2 }}'
        LEVEL_3: '${{ inputs.LEVEL_3 }}'
        RELEASE_BRANCHES_REGEX: '${{ inputs.RELEASE_BRANCHES_REGEX }}'
        PRERELEASE_BRANCHES_REGEX: '${{ inputs.PRERELEASE_BRANCHES_REGEX }}'
        DEBUG: '${{ inputs.DEBUG }}'
      run: |
        function parse_semantic_release_tag { #-> (tag: string)
          # extract major/minor/patch and channel verion tag
          if [[ $1 =~ (v([0-9]+)\.([0-9]+)\.([0-9]+)(-([a-zA-Z]+)\.([0-9]+))?)(-([0-9]+))?(-(.+))? ]]; then
            last_version="${BASH_REMATCH[1]}"
            last_channel="${BASH_REMATCH[6]}"

            major_version="${BASH_REMATCH[2]}"
            minor_version="${BASH_REMATCH[3]}"
            patch_version="${BASH_REMATCH[4]}"
            channel_version="${BASH_REMATCH[7]:-0}"

            nb_commit_since_last_release="${BASH_REMATCH[9]:-0}"
          else
            major_version="0"
            minor_version="0"
            patch_version="0"
            channel_version="0"
            nb_commit_since_last_release="0"
          fi
        }

        if [[ "$DEBUG" == "all" ]]; then set_debug_mode='set -xe'; fi
        $set_debug_mode

        CI_COMMIT_BRANCH="${GITHUB_REF#refs/heads/}"

        # Fetch git tags and commits.
        git fetch --all --tags >> /dev/null
        # remove the --depth=1 made by action/checkout@v3
        git fetch --unshallow >> /dev/null

        # find last tag from the current commit sha
        _last_tag_info=$(git describe --tags ${{ github.sha }} || true)

        parse_semantic_release_tag "$_last_tag_info"

        if [[ $CI_COMMIT_BRANCH =~ $PRERELEASE_BRANCHES_REGEX && "$last_channel" != "" && "$last_channel" != "$CI_COMMIT_BRANCH" ]]; then
          parse_semantic_release_tag "$(git describe --tags --match "v*.*.*-${CI_COMMIT_BRANCH}.*")"
        fi

        diff_path="--all"
        if [ $last_version ]; then
          diff_path="${last_version}.."
        fi
        commit_list="$(git rev-list --oneline $diff_path --format=%s --no-commit-header)"
        [ $DEBUG ] && echo "${commit_list}"

        correct="false"
        level=0
        while IFS= read -r commit; do
          [ $DEBUG ] && echo "commit=$commit"
          # Extract the commit type
          commit_prefix="${commit//:*}"
          [ $DEBUG ] && echo "commit_prefix=$commit_prefix"

          # Check if commit type is breaking changes
          if [ "$level" -lt "3" ] && [[ $commit_prefix =~ $LEVEL_3 ]]; then
            correct="true"
            level=3
            [ $DEBUG ] && echo "level=$level"
          # Check if prefix is in the array of level 2 prefix
          elif [ "$level" -lt "2" ] && [[ $commit_prefix =~ $LEVEL_2 ]]; then
            correct="true"
            level=2
            [ $DEBUG ] && echo "level=$level"
          # Check if prefix is in the array of level 1 prefix
          elif [ "$level" -lt "1" ] && [[ $commit_prefix =~ $LEVEL_1 ]]; then
            correct="true"
            level=1
            [ $DEBUG ] && echo "level=$level"
          # Check if prefix is in the array of level 0 prefix
          elif [[ $commit_prefix =~ $LEVEL_0 ]]; then
            correct="true"
            [ $DEBUG ] && echo "level=$level"
          fi
        done <<< "$commit_list"

        if [[ ${CI_COMMIT_BRANCH} =~ $RELEASE_BRANCHES_REGEX && $channel_version -eq 0 || $channel_version -eq 0 ]]; then
          if [ "$level" -eq "3" ]; then
            # Increment major version tag
            echo $(( major_version++ )) >> /dev/null
          elif [ "$level" -eq "2" ]; then
            # Increment minor version tagc
            echo $(( minor_version++ )) >> /dev/null
          elif [ "$level" == "1" ]; then
            # Increment patch version tag
            echo $(( patch_version++ )) >> /dev/null
          fi
        fi
        if [[ "$level" -gt "0" && ${CI_COMMIT_BRANCH} =~ $PRERELEASE_BRANCHES_REGEX ]]; then
          # Increment channel version tag
          echo $(( channel_version++ )) >> /dev/null
        fi

        # If prefix is not found, then check ALLOW_FAILURE and fail job when needed.
        if [[ "$ALLOW_FAILURE" == "true" && "$correct" == "false" ]]; then
          echo "The commit type '$commit_prefix' didn't exist in the commit message"
          exit 2
        fi

        # If branch is release branch
        if [[ ${CI_COMMIT_BRANCH} =~ $RELEASE_BRANCHES_REGEX ]]; then
          next_version="${major_version}.${minor_version}.${patch_version}"
          if [[ "$last_version" != "v${major_version}.${minor_version}.${patch_version}" ]]; then
            MUST_RELEASE=true
          fi

        # If branch is pre-release branch
        elif [[ ${CI_COMMIT_BRANCH} =~ $PRERELEASE_BRANCHES_REGEX ]]; then
          next_version="${major_version}.${minor_version}.${patch_version}-${CI_COMMIT_BRANCH}.${channel_version}"
          if [[ "$last_version" != "v${major_version}.${minor_version}.${patch_version}-${CI_COMMIT_BRANCH}.${channel_version}" ]]; then
            MUST_RELEASE=true
            echo 'IS_PRE_RELEASE=true' >> $GITHUB_OUTPUT
          fi

        # If branch is other branch
        elif [[ "$ALLOW_FAILURE" == "true" ]]; then
          echo "Will not update the version because current branch (${CI_COMMIT_BRANCH}) is not part of the release branches or pre-release branches."
          exit 3
        fi

        search_tag="git tag --list v${next_version}"
        if [ $MUST_RELEASE ] && [ -z "search_tag" ]; then
            echo 'WILL_RELEASE=true' >> $GITHUB_OUTPUT
        fi

        echo "VERSION=${next_version}" >> $GITHUB_OUTPUT
