name: Tests
on:
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get-Version
      id: get-version
      uses: ./
      with:
        RELEASE_BRANCHES_REGEX: '^(stable)$'
        ALLOW_FAILURE: false
        DEBUG: all

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "will_release: ${{ steps.get-version.outputs.WILL_RELEASE }}"
        echo "tag_name: v${{ steps.get-version.outputs.VERSION }}"
        echo "release_name: v${{ steps.get-version.outputs.VERSION }}"
        echo "body: v${{ steps.get-version.outputs.VERSION }}"
        echo "prerelease: ${{ steps.get-version.outputs.IS_PRE_RELEASE }}"
        echo "changelog: \n\n=== ${{ steps.get-version.outputs.CHANGELOG }} \n\n==="
